### ISSUE TITLE
Issue with rendering scientific notation in "raw-data" view

### ISSUE THREAD

**Issue by GypsyBojangles** [opendatacube/datacube-explorer#223]
The "raw" output of explorer generates malformed scientific "e" notation numbers when the digit right of the floating point is zero by truncating it.

Observable here: [https://explorer.sandbox.dea.ga.gov.au/product/ga_s2a_ard_nbar_granule.odc-product.yaml](https://explorer.sandbox.dea.ga.gov.au/product/ga_s2a_ard_nbar_granule.odc-product.yaml) in the spectral_definition for the nbar_swir_2 band

```
- name: nbar_swir_2
  dtype: int16
  units: '1'
  nodata: -999
  aliases:
  - nbar_band_11
  - nbar_B11
  - nbar_Band11
  spectral_definition:
    response:
    - 7e-06
    - 7e-06
    - 8e-06
```

should be:

```
- name: nbar_swir_2
  dtype: int16
  units: '1'
  nodata: -999
  aliases:
  - nbar_band_11
  - nbar_B11
  - nbar_Band11
  spectral_definition:
    response:
    - **7.0e-06**
    - **7.0e-06**
    - **8.0e-06**
```
