### ISSUE TITLE
Some pages don't use the new datetime logic

### ISSUE THREAD

**Issue by jeremyh** [opendatacube/datacube-explorer#352]
(As reported by @alexgleith on Slack)

Some of Explorer's html templates call datacube's `Dataset.center_time` function directly to display the day. 

They should be updated to use the  [new day logic](https://github.com/opendatacube/datacube-explorer/pull/341) of Explorer's backend.

---

Can be reproduced by adding the dataset from Africa:
```
❯ datacube product add 'https://explorer.dev.digitalearth.africa/products/rainfall_chirps_daily.odc-product.yaml'
❯ datacube dataset add 'https://explorer.dev.digitalearth.africa/dataset/35cbccee-cb07-51cf-85d2-6d2948957544.odc-metadata.yaml'
```

Which has datestrings:
```
datetime: 2019-05-15T00:00:00Z
dtr:end_datetime: 2019-05-31T23:59:59Z
dtr:start_datetime: 2019-05-31T00:00:00Z 
```
(Note that the `datetime` doesn't fall inside the `start`/`end` time.. I don't know if that's valid, but it doesn't seem to be causing this issue.)

It incorrectly shows the 23rd of May on the dataset page as the date:

![Screenshot from 2021-12-20 16-47-24](https://user-images.githubusercontent.com/25688/146717939-1986721f-7e72-43dd-9444-43d682b4686c.png)

... but the time is correct in Explorer's database backend:

```
select * from cubedash.dataset_spatial where id ='35cbccee-cb07-51cf-85d2-6d2948957544';`
```

**Comment by pindge** [comment]
odc stores the metadata as follows, the beginning time has been adjusted to ` '2019-05-15T00:00:00+00:00',` which differs to the dataset metadata, `23rd` is the correct `center_dt`

```
root@e2ea6f2165ae:/code# datacube dataset search id = '35cbccee-cb07-51cf-85d2-6d2948957544'
id: 35cbccee-cb07-51cf-85d2-6d2948957544
product: rainfall_chirps_daily
status: active
locations:
- file://example.com/test_dataset/
fields:
    cloud_cover: null
    creation_time: 2021-12-17 02:30:32.725683+00:00
    crs_raw: epsg:4326
    dataset_maturity: null
    format: GeoTIFF
    instrument: null
    label: null
    lat: {begin: -40.000001192092896, end: 40.0}
    lon: {begin: -20.0, end: 55.00000111758709}
    platform: null
    product_family: null
    region_code: null
    time: {begin: '2019-05-15T00:00:00+00:00', end: '2019-05-31T23:59:59+00:00'}
```

whereas explorer table stores the `center_dt` as per dataset metadata

```
select * from cubedash.dataset_spatial where id ='35cbccee-cb07-51cf-85d2-6d2948957544';`
                  id                  | dataset_type_ref |      center_time       |         creation_time         | region_code | size_bytes |                                                                                             footprint                                                                                              
--------------------------------------+------------------+------------------------+-------------------------------+-------------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 35cbccee-cb07-51cf-85d2-6d2948957544 |               32 | 2019-05-15 00:00:00+00 | 2021-12-17 02:30:32.725683+00 |             |            | 0103000020E6100000010000000500000000000000000034C0000000000000444000000000000034C00000000A000044C00000600900804B400000000A000044C00000600900804B40000000000000444000000000000034C00000000000004440
```

This finding has lead to 2 issues raised in `datacube-core` https://github.com/opendatacube/datacube-core/issues/1265 and https://github.com/opendatacube/datacube-core/issues/1264
